version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 3306:5432
    environment:
      POSTGRES_DB: Cirmax
      POSTGRES_USER: cirmax
      POSTGRES_PASSWORD: cirmaxp

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
